spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/basicmall_pms
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.56.10
    port: 6379
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 12000

logging:
  level:
    com.wushiyuan.basicmall: debug
