server:
  port: 35000

spring:
  cloud:
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: basicmall-hello
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: basicmall-third-party
